version: 2

includes:
  - from_url:
      url: https://raw.githubusercontent.com/ory/xgoreleaser/master/build.tmpl.yml

before:
  hooks:
    - go mod download
    - git checkout -- go.sum go.mod
    - "curl -Lo /tmp/cosign.key
      https://raw.githubusercontent.com/ory/xgoreleaser/master/cosign.key"
    - "curl -Lo /tmp/cosign.pub
      https://raw.githubusercontent.com/ory/xgoreleaser/master/cosign.pub"

variables:
  brew_name: oathkeeper
  brew_description: "The Ory Identity and Access Proxy (Ory Oathkeeper)"
  buildinfo_hash: "github.com/aaishahhamdha/oathkeeper/x.Commit"
  buildinfo_tag: "github.com/aaishahhamdha/oathkeeper/x.Version"
  buildinfo_date: "github.com/aaishahhamdha/oathkeeper/x.Date"
  dockerfile_alpine: ".docker/Dockerfile-alpine"
  dockerfile_static: ".docker/Dockerfile-distroless-static"

project_name: oathkeeper
